### ISSUE TITLE
tGoogleSearchAnalytics Does not appear to install

### ISSUE THREAD

**Issue by scottcattell** [jrosell/tGoogleSearchAnalytics#2]
Hi,

I downloaded the thediar-talendcomp-googlesearchanalytics-0.0.1-SNAPSHOT.car file and attempted to install it as outlined in the installation notes, however, all items to be installed already existed:

![image](https://user-images.githubusercontent.com/46191909/90887866-12a6f380-e3ad-11ea-8f56-1434d402dbbf.png)

However, there is still no component tGoogleSearchAnalytics within my Talend Studio.

Any assistance would be greatly appreciated.
Scott

**Comment by jrosell** [comment]
I supose you arelady run:  ./mnvw clean install 
If you completly close Talend and open it again, you should see tGoogleSearchAnalyticsInput component on your Palette.

I used Talend 7.1.1. I will try to reproduce your steps with Talend 7.3.1.

**Comment by jrosell** [comment]
Please, remove /Studio from your  /path/to/my/talend

I've just updated [README](https://github.com/jrosell/tGoogleSearchAnalytics/blob/master/README.md). Now it will be easier to follow :)
